### ISSUE TITLE
Two places to calculate disparity map in the project

### ISSUE THREAD

**Issue by xgd** [sniklaus/3d-ken-burns#11]
Hi,
Love your project.
After reading your code, I am a little confused for generating the disparity map.
From the code, there seems two different ways to calculate disparity map: 

1. common.py
https://github.com/sniklaus/3d-ken-burns/blob/a75ac8060ff93b316ec702cb24ca733c15899a69/common.py#L11
2. depthestim.py
https://github.com/sniklaus/3d-ken-burns/blob/a75ac8060ff93b316ec702cb24ca733c15899a69/depthestim.py#L71

Can you kindly explain why the differences?
Thanks.

**Comment by sniklaus** [comment]
Thank you for being interested in our work! The second reference is to the estimate from the neural network, the first is the same but normalized such that the disparity is within `0` and `dblBaseline`. There is a scale-ambiguity when dealing with depth / disparity, so the first reference is just making sure that the disparity is at least within a well-defined range.

**Comment by xgd** [comment]
Thank you for your answer.
For second reference, after getting the disparity map from neural network, there are two more steps to process the disparity map.
1. multiply by " (max(tensorImage.size(2), tensorImage.size(3)) / 256.0)"
2. when generating the png,  "numpyDisparity / dblBaseline * 255.0"
What are these two steps for?

**Comment by sniklaus** [comment]
Disparity is resolution-dependent. If you capture a stereo image with the same setup but at twice the resolution, everything will be twice as far apart in terms of pixels. The first step is to account for that. When visualizing the disparity as an image, you need to adjust its range to [0, 255] and that is what the second step is doing.

**Comment by xgd** [comment]
Great. Thanks again.
