### ISSUE TITLE
CPU inference ?

### ISSUE THREAD

**Issue by axelbellec** [sniklaus/3d-ken-burns#13]
Congratulations for you paper, and thanks for open sourcing this very effective work. I have one question about your python implementation, hope you can give some advice.

- Is it possible to process 3d-ken-burns effect without using CUDA (just by doing some CPU inference) ?

Thanks,

Axel

**Comment by sniklaus** [comment]
I am afraid that I have no plans of providing CPU-based inference code. I understand the appeal of it, but I unfortunately do not have the time to make the necessary changes to the following CUDA functions.

https://github.com/sniklaus/3d-ken-burns/blob/a75ac8060ff93b316ec702cb24ca733c15899a69/common.py#L362
https://github.com/sniklaus/3d-ken-burns/blob/a75ac8060ff93b316ec702cb24ca733c15899a69/common.py#L452
https://github.com/sniklaus/3d-ken-burns/blob/a75ac8060ff93b316ec702cb24ca733c15899a69/common.py#L513
https://github.com/sniklaus/3d-ken-burns/blob/a75ac8060ff93b316ec702cb24ca733c15899a69/common.py#L621

**Comment by axelbellec** [comment]
Thanks for your answer.

**Comment by divyajaincs** [comment]
What changes we need to do to run this model with CPU for inference?

**Comment by sniklaus** [comment]
There is no way to run CUDA code on CPUs as far as I know, so you would have to reimplement the affected parts of the code.
