### ISSUE TITLE
segmentation fault .

### ISSUE THREAD

**Issue by lulu1315** [sniklaus/3d-ken-burns#19]
running on KDE Neon (Ubuntu 18.04)
NVIDIA Corporation GM200 [GeForce GTX TITAN X] (rev a1)
Cuda compilation tools, release 10.2, V10.2.89
Cudnn 7.6.5
Python 3.6.9
torch 1.5.0a0+90a259e (compiled from source)
torchvision 0.6.0a0+28b7f8a (compiled from source)

command : python3 autozoom.py --in ./images/doublestrike.jpg --out ./autozoom.mp4
i've got a Segmentation fault when arriving on this line in common.py in process_load()
tensorDisparity = disparity_estimation(tensorImage)

thanks for your help.
luc

**Comment by sniklaus** [comment]
It seems like you are using a pre-release / alpha version of PyTorch and TorchVision. Have you tried one of the official releases?

**Comment by lulu1315** [comment]
hello and thank you.it works now.

switched to cuda 10.1 and corresponding Cudnn
torch==1.4.0
torchvision==0.5.0
cupy-cuda101==7.1.1

thank you very much for the code.
luc

**Comment by sniklaus** [comment]
Thanks for letting me know, I am happy to hear that!
