### ISSUE TITLE
any chance to release training code?

### ISSUE THREAD

**Issue by nile649** [sniklaus/3d-ken-burns#20]

**Comment by sniklaus** [comment]
I am afraid that I currently have no plans to do so, my apologies.

**Comment by nile649** [comment]
Not even dataset used for the training?

**Comment by sniklaus** [comment]
I am planning to release the dataset since I acknowledge its usefulness for the research community. I have yet to start the necessary paperwork though and unfortunately have no estimate of when I will be able to release it.

**Comment by andriyrizhiy** [comment]
@sniklaus When you are planning to release the dataset?

**Comment by sniklaus** [comment]
I will update #25 once we have more information on the release of the dataset. :+1:
