### ISSUE TITLE
Depth adjustment

### ISSUE THREAD

**Issue by dfrumkin** [sniklaus/3d-ken-burns#22]
Hello Simon! 
Do you plan on adding depth adjustment to the depth estimation script?  I am interested.

"Please note that this script does not perform the depth adjustment, I will add it to the script at a later time should people end up being interested in it."

**Comment by dfrumkin** [comment]
Is it just a one-liner?

`tensorDisparity = disparity_adjustment(tensorImage, tensorDisparity)`

**Comment by sniklaus** [comment]
Yes, you can just add that line as follows.

```
tensorDisparity = disparity_estimation(...)
tensorDisparity = disparity_adjustment(tensorImage, tensorDisparity)
tensorDisparity = disparity_refinement(...)
```

Let me know in case you have any issues with this, thanks!
