### ISSUE TITLE
Benchmark results

### ISSUE THREAD

**Issue by dfrumkin** [sniklaus/3d-ken-burns#23]
You write that "the depth boundary error is currently different from the paper".  I see that the huge dbe_com can be ignored; however, there are noticeable differences in some other metrics as well.  Do you know why?

```
abs_rel =  0.09667361210538511
sq_rel  =  0.08968517555964581
rms     =  0.468931547303287
log10   =  0.04028934128953222
thr1    =  0.9042070992913529
thr2    =  0.9735211480731727
thr3    =  0.9914000487947728
dde_0   =  0.9348635887380082
dde_m   =  0.02829501122683011
dde_p   =  0.0368414000351617
dbe_acc =  2.027432278515633
dbe_com =  29.32951945280528
pe_fla  =  2.1928497290019897
pe_ori  =  10.243341646515104
```

**Comment by sniklaus** [comment]
Would you mind clarifying what the issue is? Aside from the depth boundary error, which is expected to differ, all other metrics match exactly what we report in our paper?

**Comment by dfrumkin** [comment]
You are right.  I got confused because I looked at NYU v2 metrics...  Thanks a lot!
