### ISSUE TITLE
Curious About Training Dataset

### ISSUE THREAD

**Issue by JasonLSC** [sniklaus/3d-ken-burns#25]
Thank you for your impressive work. I am really curious about how to create training pairs for color and depth images inpainting. 
Wonder if you would like to share a link to training dataset in the future?

**Comment by andriyrizhiy** [comment]
Can you get one sample from your dataset?

**Comment by sniklaus** [comment]
You can find one here: http://content.sniklaus.com/kenburns/dataset.zip

**Comment by andriyrizhiy** [comment]
did you use scalable or original targets? How did you invert your target?

**Comment by sniklaus** [comment]
We supervise on inverse depth according to: `(256 * 40) / depth`

**Comment by oljike** [comment]
Hi, Simon! Thanks for your work! Do you have any updates on dataset release date?

**Comment by sniklaus** [comment]
Good news, the dataset is now available! Please see the readme for more details, thank you for your patience!
