### ISSUE TITLE
Question about loss func for depth estimation

### ISSUE THREAD

**Issue by andriyrizhiy** [sniklaus/3d-ken-burns#28]
![image](https://user-images.githubusercontent.com/41432542/76852541-3beab300-6854-11ea-917e-566cc48e3ba0.png)
Can you show the implementation of the loss function?
Because i don't understand how "i,j" change for each "h" in grad part of loss

**Comment by sniklaus** [comment]
You can find an implementation of this loss in the DeMoN repository.

https://github.com/lmb-freiburg/demon/blob/40806b2b9541a6eb0d6275cc548a53eebbf01273/python/depthmotionnet/v2/losses.py#L57
