### ISSUE TITLE
Error when trying to generate from the image

### ISSUE THREAD

**Issue by miaodd98** [sniklaus/3d-ken-burns#32]
Hello! I'm interested in your work and try to use your code to generate a 3D Ken Burns video. But there is a problem when I try to generate it. My cuda version is 10.2 and all other packs has been installed. The environment is Win 10.
The error is below:

> Traceback (most recent call last):
>   File "autozoom.py", line 88, in <module>
>     'objFrom': objFrom
>   File "<string>", line 116, in process_autozoom
>   File "<string>", line 433, in render_pointcloud
>   File "cupy\util.pyx", line 81, in cupy.util.memoize.decorator.ret
>   File "<string>", line 293, in launch_kernel
> IndexError: list index out of range

I wonder why this happens and hope for your reply. Thanks a lot!
BTW, I'm curious about the training method. If there is any possibility for you to release the training code. Just asking.

**Comment by miaodd98** [comment]
Problem solved. In Win10, CUDA_HOME environment variable is called CUDA_PATH. Change every CUDA_HOME to CUDA_PATH if your system is Win10 in common.py line 292 to 296.

**Comment by sniklaus** [comment]
I am happy you ended up figuring it out, and thank you for sharing how you fixed it!

**Comment by jackiemar** [comment]
> Problem solved. In Win10, CUDA_HOME environment variable is called CUDA_PATH. Change every CUDA_HOME to CUDA_PATH if your system is Win10 in common.py line 292 to 296.

thanks, it has help me solving the same problem! 
haha, then I change the system variable from "CUDA_PATH" TO "CUDA_HOME";(not recommended)
![Image 002](https://user-images.githubusercontent.com/35718238/151677028-37616105-1d1b-4dbc-97ff-4220222ff180.png)
