### ISSUE TITLE
RuntimeError: view size is not compatible 

### ISSUE THREAD

**Issue by thesoulharmonic** [sniklaus/3d-ken-burns#33]
When I try and run the colab of this I'm getting and error on the final step of

> Traceback (most recent call last):
>   File "autozoom.py", line 76, in <module>
>     process_load(npyImage, {})
>   File "<string>", line 10, in process_load
>   File "<string>", line 128, in disparity_refinement
>   File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
>     result = self.forward(*input, **kwargs)
>   File "<string>", line 94, in forward
> RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

Do you know what this might be?

Thank you

**Comment by skabbit** [comment]
Got the same error on Google Colab run.

**Comment by sniklaus** [comment]
Which Colab are you using and what is the PyTorch version? Thanks!

**Comment by thesoulharmonic** [comment]
This is the Colab - https://colab.research.google.com/github/agmm/colab-3d-ken-burns/blob/master/automatic-3d-ken-burns.ipynb but it happens on the other 2 also.

**Comment by skabbit** [comment]
I tried all three Colabs listed in README.
Google Colab Pro, Standart GPU runtime.
I also tried to rollback to commit bde67588ff2b0247068fc2fe4419619d47e3a228, supposed trained network and code are unsynced, but still no luck.

**Comment by skabbit** [comment]
Tried c6e70de139e39ad1d25d8ad2dea2922826770e89 also, but got the same error.

**Comment by sniklaus** [comment]
I just pushed some changes that were necessary when using PyTorch 1.5, pleas try rerunning the Colab from the beginning.

**Comment by thesoulharmonic** [comment]
That seems to have fixed it for me. Thank you

**Comment by sniklaus** [comment]
I am happy to hear that, thank you for confirming!

**Comment by skabbit** [comment]
Yep, everything works now! Thank you!
