### ISSUE TITLE
Meaning of parameters in meta data json files

### ISSUE THREAD

**Issue by waps101** [sniklaus/3d-ken-burns#39]
For the synthetic depth/normal dataset, there is a meta data json file included with the RGB images. This contains two parameters: intSample and fltFov. Could you explain what these mean? Ideally, I would like to be able to compute camera intrinsics in the form of focal length/principal point or a K matrix. Any guidance on doing this from the json files would be appreciated.

**Comment by sniklaus** [comment]
The `intSample` has little meaning outside the framework that I used to create the dataset. The reason why I included the meta file is the `fltFov` which is the field of view. You can derive the focal length from the field of view, the principal point is in the center, and the pinhole camera model is not subject to distortions. Please let me know in case there are any missing intrinsics.

**Comment by waps101** [comment]
I assume this is horizontal/vertical field of view as opposed to diagonal?

**Comment by sniklaus** [comment]
You are correct.

**Comment by sniklaus** [comment]
You may also find this interesting / useful: https://github.com/sniklaus/3d-ken-burns/issues/37#issuecomment-635525362

**Comment by Binyr** [comment]
asdf-flying/00656-meta.json is empty.

**Comment by sniklaus** [comment]
Thanks for reporting!

I just downloaded `asdf-flying` and the `00656-meta.json` there seemed perfectly fine:
```
{"intSample": 656, "fltFov": 84.527916}
```

Did something during your download or during unzipping go awry by chance?
