### ISSUE TITLE
Distorting the depth when training the depth refinement network

### ISSUE THREAD

**Issue by seokg** [sniklaus/3d-ken-burns#43]
Hi, thank you for the wonderful work.

I have a question about the distortion mentioned in _Section 3.1.3 Depth Refinement._
It states that when training the depth refinement network, 

> _"we downsample and distort the ground truth depth to simulate the coarse prediction depth maps ..."_.

Could you explain a bit more details on how the distortion is conducted to the ground truth depth?

**Comment by sniklaus** [comment]
Thank you for your kind words!

We used elastic distortions for this: https://github.com/mdbloice/Augmentor#elastic-distortions

Specifically: `Augmentor.Operations.Distort(probability=0.9, grid_width=16, grid_height=16, magnitude=1)`
