### ISSUE TITLE
Ground truth resolution

### ISSUE THREAD

**Issue by dfrumkin** [sniklaus/3d-ken-burns#46]
Hello Simon!
How do you reach the resolution of 1024 for the largest dimension if the resolution of the synthetic dataset is only 512x512?

**Comment by sniklaus** [comment]
The refinement network was trained to upsample a 128 input to a 512 output. At test time, it is applied to a 256 input such that it gives a 1024 output. This seems to work reasonably well despite the different resolutions.

**Comment by dfrumkin** [comment]
Thank you very much for your response!  You train the refinement network not only independently of the coarse network (using elastic deformations instead of the typical input you would get), but also on a different resolution.  Very interesting.
