### ISSUE TITLE
Can this expand to arbitrary camera motion? eg. left-right swing or circle swing?

### ISSUE THREAD

**Issue by zerollzeng** [sniklaus/3d-ken-burns#47]
Great job! I was wondering can we add more motion support base on this algorithm? the output is fantastic!

**Comment by sniklaus** [comment]
Thank you for your kind words! While it would be possible to add more features like this, I am afraid that I have to refrain from adding them since it would be a potential conflict of interest with my employment at Adobe. My apologies.
