### ISSUE TITLE
Patent question

### ISSUE THREAD

**Issue by xiong-jie-y** [sniklaus/3d-ken-burns#49]
Hi, 

Thank you for nice repository.
The both depth pipeline and inpainting algorithm are awesome.

I have a question.
Are anything in the proposed methods in this paper patented?
https://arxiv.org/abs/1909.05483

**Comment by sniklaus** [comment]
Thank you for the kind words! We submitted a patent application with the title "3D MOTION EFFECT FROM A 2D IMAGE" but since it got filed by someone else I am unable to see what the status is, my apologies.

**Comment by xiong-jie-y** [comment]
Thank you! I will check it out!
