### ISSUE TITLE
Could I run on MacBook without CUDA?

### ISSUE THREAD

**Issue by adriantabirta** [sniklaus/3d-ken-burns#52]
I would like to test it on macbook, it is possible not to use Cuda? It is possible to make an update and use only CPU?

**Comment by sniklaus** [comment]
Thank you for your interest in our work! You can check #13 for a list of changes that would have to be made to for being able to use a CPU, there are quite a few. I understand the appeal of it, but I unfortunately do not have the time to make these changes at the moment, my apologies.
