### ISSUE TITLE
Getting IndexError: list index out of range while running default command

### ISSUE THREAD

**Issue by PotatoHate** [sniklaus/3d-ken-burns#53]
Using `python autozoom.py --in ./images/doublestrike.jpg --out ./autozoom.mp4` command to run the code but i am getting IndexError: list index out of range. 
![image](https://user-images.githubusercontent.com/10143526/131144653-0141514b-57e4-43a2-aa19-b64c9d5785e8.png)

# This is the package list i have installed:

> blas=1.0=mkl
> ca-certificates=2021.7.5=haa95532_1
> cached-property=1.5.2=py_0
> certifi=2021.5.30=py37haa95532_0
> cffi=1.14.6=py37h2bbff1b_0
> charset-normalizer=2.0.4=pypi_0
> click=8.0.1=pyhd3eb1b0_0
> colorama=0.4.4=pypi_0
> cudatoolkit=10.1.243=h74a9793_0
> cudnn=7.6.5=cuda10.1_0
> cupy=8.3.0=py37hd4ca531_0
> decorator=4.4.2=pypi_0
> fastrlock=0.6=py37hd77b12b_0
> flask=1.1.2=pyhd3eb1b0_0
> freetype=2.10.4=hd328e21_0
> gevent=21.8.0=py37h2bbff1b_1
> greenlet=1.1.1=py37hd77b12b_0
> h5py=3.2.1=py37h3de5c98_0
> hdf5=1.10.6=h7ebc959_0
> icc_rt=2019.0.0=h0cc432a_1
> idna=3.2=pypi_0
> imageio=2.9.0=pypi_0
> imageio-ffmpeg=0.4.5=pypi_0
> importlib-metadata=3.10.0=py37haa95532_0
> intel-openmp=2021.3.0=haa95532_3372
> itsdangerous=2.0.1=pyhd3eb1b0_0
> jinja2=3.0.1=pyhd3eb1b0_0
> jpeg=9b=hb83a4c4_2
> libpng=1.6.37=h2a8f88b_0
> libtiff=4.2.0=hd0e1b90_0
> lz4-c=1.9.3=h2bbff1b_1
> markupsafe=2.0.1=py37h2bbff1b_0
> mkl=2021.3.0=haa95532_524
> mkl-service=2.4.0=py37h2bbff1b_0
> mkl_fft=1.3.0=py37h277e83a_2
> mkl_random=1.2.2=py37hf11a4ad_0
> moviepy=1.0.3=pypi_0
> ninja=1.10.2=h6d14046_1
> numpy=1.20.3=py37ha4e8547_0
> numpy-base=1.20.3=py37hc2deb75_0
> olefile=0.46=py37_0
> opencv-contrib-python=4.5.3.56=pypi_0
> openssl=1.1.1k=h2bbff1b_0
> pillow=8.3.1=py37h4fa10fc_0
> pip=21.2.4=pypi_0
> proglog=0.1.9=pypi_0
> pycparser=2.20=py_2
> pyreadline=2.1=py37_1
> python=3.7.11=h6244533_0
> pytorch=1.6.0=py3.7_cuda101_cudnn7_0
> requests=2.26.0=pypi_0
> scipy=1.6.2=py37h66253e8_1
> setuptools=52.0.0=py37haa95532_0
> six=1.16.0=pyhd3eb1b0_0
> sqlite=3.36.0=h2bbff1b_0
> tk=8.6.10=he774522_0
> torchvision=0.7.0=py37_cu101
> tqdm=4.62.2=pypi_0
> typing_extensions=3.10.0.0=pyh06a4308_0
> urllib3=1.26.6=pypi_0
> vc=14.2=h21ff451_1
> vs2015_runtime=14.27.29016=h5e58377_2
> werkzeug=1.0.1=pyhd3eb1b0_0
> wheel=0.37.0=pyhd3eb1b0_0
> wincertstore=0.2=py37_0
> xz=5.2.5=h62dcd97_0
> zipp=3.5.0=pyhd3eb1b0_0
> zlib=1.2.11=h62dcd97_4
> zope=1.0=py37_1
> zope.event=4.5.0=py37_0
> zope.interface=5.4.0=py37h2bbff1b_0
> zstd=1.4.9=h19a0ad4_0
>

**Comment by sniklaus** [comment]
My apologies, but I am not a Windows user and have no idea how to configure that. :sweat_smile: 

I am closing this issue for now since it seems like you figured it out. :+1:
