### ISSUE TITLE
unable to run the interface.py

### ISSUE THREAD

**Issue by nigamelastic** [sniklaus/3d-ken-burns#6]
**While running the build with :**
1. cuda 10.1 
2. python36 
3. OS: Windows 10

I get the following error.

`Traceback (most recent call last):
  File ".\interface.py", line 45, in <module>
    exec(open('./models/disparity-estimation.py', 'r').read())
  File "<string>", line 195, in <module>
  File "<my python virtual env for python 36>", line 419, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: './models/disparity-estimation.pytorch'`

I am not sure why its looking for pytoch when the input is .py may be i am missing something , Please let me know

**Comment by sniklaus** [comment]
Have you done all the steps that are outline in the setup section?

**Comment by nigamelastic** [comment]
Actually I realized my mistake. Since I am running it on windows I didn't rename the disparity estimation and simply downloaded it. Now since I have renamed the file it works perfectly. Thanks a lot for the swift response though :)

**Comment by sniklaus** [comment]
Good news, I am happy you got it to work!
