### ISSUE TITLE
Pass together image and precomputed .npy map

### ISSUE THREAD

**Issue by C00reNUT** [sniklaus/3d-ken-burns#69]
Hello, 

may I ask you is there possibly some way to use cli in a way that I would pass together image and it's matching pre-computed depth map? Something like: 

`python autozoom.py --in ./images/doublestrike.jpg --depth depth.npy --out ./autozoom.mp4`

I can see from code that it's not possible directly, since there is no arg option for depth.

I would modify the code, but I am not very familiar with the algorithm, so I am not sure which variable should I change/aim for...

Thank you!

**Comment by sniklaus** [comment]
Just pushed [e629394](https://github.com/sniklaus/3d-ken-burns/commit/e629394b13e61c04ac3a7d4043eb4cc04ffffd4a) with this very feature, let me know whether or not it works for you. :+1:
