### ISSUE TITLE
Can't seem to run this in Colab

### ISSUE THREAD

**Issue by cyrilzakka** [sniklaus/3d-ken-burns#7]
I can't seem to run this on Colab. I'm stuck at trying to set CUDA_HOME but to no avail. Any advice?

**Comment by cyrilzakka** [comment]
%env CUDA_HOME=/usr/local/cuda seems to be the way to go

**Comment by sniklaus** [comment]
Thank you for sharing this information! For everyone looking, this Colab notebook seems to be a good start: https://colab.research.google.com/drive/1XcDFtte7KpI8Q3w90-mAd1qSFMkKFEpt
